name: test_watcher
description: A process that watches for changes in your Flutter test directory and runs them automatically.
version: 0.0.1
repository: https://github.com/Dinip/test_watcher

environment:
  sdk: ^3.4.4

dependencies:
  ansi_styles: ^0.3.2+1
  args: ^2.6.0
  watcher: ^1.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
